### ISSUE TITLE
Build error (Couldn't find artifact network.thunder:thunder-core.jar:0.1)

### ISSUE THREAD

**Issue by lacksfish** [blockchain/thunder#18]
> Downloaded: http://repo.maven.apache.org/maven2/com/google/guava/guava/18.0/guava-18.0.jar (2204 KB at 1298.4 KB/sec)
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.513s
> [INFO] Finished at: Mon May 16 17:14:50 CEST 2016
> [INFO] Final Memory: 7M/150M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project thunder-clientgui: Could not resolve dependencies for > project network.thunder:thunder-clientgui:jar:0.1: Could not find artifact network.thunder:thunder-core:jar:0.1 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following > articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> cp: cannot stat ‘thunder-clientgui/target/thunder-clientgui-0.1.jar’: No such file or directory
> cp: cannot stat ‘thunder-core/target/thunder-core-0.1-jar-with-dependencies.jar’: No such file or directory

**Comment by matsjj** [comment]
Thanks for submitting the issue! 
Can you clarify which OS / Java version / Maven version you are trying to build this against?

**Comment by lacksfish** [comment]
Linux Mint 17 / Ubuntu 14.04 (x64)
______
> java --version

java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
______
> mvn --version

Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-24-generic", arch: "amd64", family: "unix"


I guess Java 1.7 is the issue I'm having. Upgrading to 1.8 right now.

**Comment by matsjj** [comment]
Thanks, yes it should not be able to build with Java 1.7. The error message you posted above looks just like the symptom of the underlying issue that it could not build thunder-core (you should find a more helpful error message further above).

**Comment by lacksfish** [comment]
Updating to Java 1.8 [using this guide](https://www.liquidweb.com/kb/how-to-install-oracle-java-8-on-ubuntu-14-04-lts/) specifically for my OS.

**Comment by matsjj** [comment]
On Unix machines you might also need OpenJFX, just to let you know.

**Comment by lacksfish** [comment]
Maven had some issues cleaning up, but a fresh pull was built successfully.
