### ISSUE TITLE
Selecting thunder address in receive field: cpu goes to and remains at 100% until closed

### ISSUE THREAD

**Issue by sumBTC** [blockchain/thunder#27]
(my first issue post on github so I hope I'm doing it right)

This happens on both my 32bit machine and my 64bit machine (Ubuntu 14.04)

So I click the Receive button and it opens.
CPU (as seen with top) goes up but then low again.
If I now select the whole address field by clicking three times fast, it selects the whole address ( like: 00000000000003e8298fdcdca7ba10a185e03feed9bcb86d26896d76020ab5c6876de992ce73bc8835eb28a8186385892ccf19b44d8c1662ae0eedaccd) but the CPU on my machine goes to 100% and stays that high. Only when I close the receive field (by clicking Close) CPU normalizes again.

On start-up I get the error messages:
libGL error: failed to authenticate magic 65
libGL error: failed to load driver: i915
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

As I wrote on Reddit, I installed by doing:
sudo apt-get install maven
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
git clone https://github.com/blockchain/thunder.git
cd thunder
./build.sh

**Comment by matsjj** [comment]
Hey, thanks for the report. I cannot reproduce it on my local machine (Mac), I will try in a VM later. 

The error message about libGL seems important, even though Google has very little to say about it. 

Either way, the wallet is rather as a demonstration of the underlying library. It also copies the address into clipboard automatically, maybe a textfield indicating that will stop people selecting in that field. 

Were you able to discover the high CPU usage elsewhere in the application?

**Comment by sumBTC** [comment]
"It also copies the address into clipboard automatically". Yes, I found that out later, nevertheless someone may want to copy an address for whatever reason. I will have a look myself during the weekend whether I can solve the issue with the error message on my computer and see if that solves the problem. In general I find opening the Receive or Send window quite slow.

(I did some transactions between different thunder wallets over my own thunder node yesterday, great feeling to be one of the first to do this!)

**Comment by matsjj** [comment]
Yes, that would be great. Opening windows is randomly very fast, but 90% of the time rather slow. 

To be honest, JavaFX is great to get some early alpha GUI, but I don't know yet if its mature enough for a final product. It lacks all OS integrations, shortcuts for copy/paste don't work, etc. But that is also where it comes down to the purpose anyways. It's great to develop the underlying library and get a feeling which API calls are good and which needs improvement, how events get handled, how async calls work out, etc. 

Great to hear that! 👍

**Comment by sumBTC** [comment]
The problem doesn't seem to be a big thing. Although I ran thunder on a 32bit and 64bit machine, the window was only displayed on my 32bit small screen notebook (through ssh, the 64bit computer display is broken and that's why I use it as a bitcoin full node). So I asked my son, who runs Debian on a 64bit computer, to install thunder also and we found out that he didn't have the problem of his CPU going to 100%. This leaves open the question of whether it's an Ubuntu Linux thing. So I started the thunder program on my 64bit machine and displayed the window on my son's 64bit machine and everything was fine. So the problem only seems to exist on my 32bit notebook which I wasn't able to solve. But even there thunder still runs but let's my CPU go to and often remain at 100%. So I would say for now we should close this issue, do you agree?

**Comment by matsjj** [comment]
Oh you are right, it is much smoother now without the blurring. Thanks a lot for finding that out, I trade that in over speed any day. 

Re: P.S. good catch, what would you consider the correct behaviour in this case? I changed it to fallback to '0' instead of empty (and catch any possible exception so the application doesn't crash), but that feels unintuitive as well. Can't make a zero payment after all, so creating a payment request with it is just confusing.

If you want, it's great to see other nodes on the network. With 0.2 we hopefully introduce persistence storage, that will make it much easier for other people to run nodes as well!

**Comment by sumBTC** [comment]
Nice to know you also confirm what is only obvious on a slow 32bit computer.

I would suggest displaying a blank QR-code but of course I'm not an insider enough to give a really good advice here. I'm just a ever complaining user :-)

Good, I will leave my thunder node running then and will upgrade to 0.2 when it's ready.

Best wishes with this important but complex project.
